# Generated by Django 5.0.6 on 2024-05-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
