# Generated by Django 5.0.6 on 2024-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(upload_to="media/audios/"),
        ),
    ]
