# Generated by Django 5.0.6 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0002_alter_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(upload_to="audios/"),
        ),
    ]
