# Generated by Django 5.0.6 on 2024-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0003_pdf_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="audio_path",
        ),
        migrations.RemoveField(
            model_name="pdf",
            name="file_path",
        ),
        migrations.AddField(
            model_name="audio",
            name="file",
            field=models.FileField(default=False, upload_to="audios/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdf",
            name="file",
            field=models.FileField(default=False, upload_to="pdfs/"),
            preserve_default=False,
        ),
    ]
