# Generated by Django 5.0.6 on 2024-05-18 14:55

import text_to_speech_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0003_alter_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(upload_to=text_to_speech_app.models.audio_upload_to),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(upload_to=text_to_speech_app.models.pdf_upload_to),
        ),
    ]
