# Generated by Django 5.0.6 on 2024-05-20 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0004_alter_audio_file_alter_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="audio",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
