# Generated by Django 5.0.6 on 2024-05-16 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "text_to_speech_app",
            "0004_remove_audio_audio_path_remove_pdf_file_path_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdf",
            old_name="upload_at",
            new_name="uploaded_at",
        ),
    ]
