# Generated by Django 5.0.6 on 2022-01-01 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0005_rename_upload_at_pdf_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="user",
        ),
    ]
