# Generated by Django 5.0.6 on 2024-05-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_to_speech_app", "0005_pdf_is_deleted_alter_audio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_to_speech_app.pdf",
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="user",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
